employename=input("enter your name")
employenameid=input("enter your id no")
designation=input("enter your designation")
salary=input("enter your salary")
experience=input("enter your expi")
address=input("enter your address")
place=input("enter your place")
pincode=input("enter your pincode")
mobileno=input("enter your mob no")
username=input("enter your username")
password=input("enter your password")
confirmpassword=input("enter your password")
if(password==confirmpassword):
    print(employename)
    print(employenameid)
    print(designation)
    print(salary)
    print(experience)
    print(address)
    print(place)
    print(pincode)
    print(mobileno)
    print(username)
    print(password)
    print(confirmpassword)
else:
    print("password and confirmpassword doesn't match")
